### ISSUE TITLE
The Plugin doesn't work with 'noremap ; :'.

### ISSUE THREAD

**Issue by rhcher** [booperlv/nvim-gomove#2]
Thank you for your great work to this plugin, I tried this plugin and everything works well. Except that this plugin does not work with specific key mappings like `'noremap ; :' 'noremap : ;'`. I would like to know if possible or necessary to fix this issue. It would not be difficult for me to change this habit, but it would be nice if this plugin could work together directly with my original configuration.

**Comment by booperlv** [comment]
I have been trying to look into this for a few now! Have to wait for the end of the holidays to get the time to be able to look into it extensively though :)

**Comment by booperlv** [comment]
Just a heads up that I have been trying to investigate this problem and can reproduce it. I will keep trying, but it seems that I'm not getting many places with my current method of investigation. Hope I can figure it out soon!

**Comment by booperlv** [comment]
@rhcher Fixed it in 5c6d2a4734d96deabe6ad8664817d0a9dd55fcfd! Sorry it took me a while.
