### ISSUE TITLE
Bindings question/suggestion

### ISSUE THREAD

**Issue by farzadmf** [booperlv/nvim-gomove#3]
Hi,

I've been using [`vim-move`](https://github.com/matze/vim-move) until now and this plugin seems to be a very good alternative to that. One feature that I like with `vim-move` is that you can just re-assign the identifier and not needing to manually include all the mapping in your config. For example, you can do `let g:move_key_modifier = 'C'` to use <kbd>CTRL</kbd> with `h, j, k, l` to move the lines.

I was wondering if something similar is possible with this plugin. And, if it's not, can you provide an example on how to map the default "smart" bindings to, say, <kbd>CTRL</kbd> instead of <kbd>ALT</kbd>. (so that <kbd>CTRL, SHIFT</kbd> would also do what <kbd>ALT, SHIFT</kbd> does by default)

And sorry if this is something that expert vim people can figure out, but I'm not that expert, so I'd appreciate the help 🙂

**Comment by booperlv** [comment]
Hello ! I have tried to implement that exact option, but I have figured that with the default mappings being <(modifier)-shift-(key)> for the duplicates, it wouldn't exactly be universal to have such an option.

Thank you for bringing this into my attention though! Will add a portion to the README for that.

For now, here's an example in vim script from my eccentric dots :)
```
nnoremap <A-m> <Plug>GoNSMLeft
nnoremap <A-,> <Plug>GoNSMDown
nnoremap <A-.> <Plug>GoNSMUp
nnoremap <A-/> <Plug>GoNSMRight

xnoremap <A-m> <Plug>GoVSMLeft
xnoremap <A-,> <Plug>GoVSMDown
xnoremap <A-.> <Plug>GoVSMUp
xnoremap <A-/> <Plug>GoVSMRight

nnoremap <A-M> <Plug>GoNSDLeft
nnoremap <A-<> <Plug>GoNSDDown
nnoremap <A->> <Plug>GoNSDUp
nnoremap <A-?> <Plug>GoNSDRight

xnoremap <A-M> <Plug>GoVSDLeft
xnoremap <A-<> <Plug>GoVSDDown
xnoremap <A->> <Plug>GoVSDUp
xnoremap <A-?> <Plug>GoVSDRight
```

**Comment by booperlv** [comment]
d118cbd0e285c0c43de3368565190766215c55aa ! I apologize this wasn't exactly the solution you wanted, but for most terminals, Ctrl and Ctrl+Shift aren't really distinguishable, and other cases would be hard to figure out. That's why I personally think that the user should configure it for themselves. If there is anything you would like to discuss or suggest though, please do reopen the issue if so desired!

**Comment by farzadmf** [comment]
Thank you @booperlv , I'll give them a try. I'm using <kbd>ALT</kbd> mappings to navigate between my `tmux` panes (and `neovim` windows), and that's why I'm using <kbc>CTRL</kbd> for moving the lines.

But the <kbd>CTRL, SHIFT</kbd> not being recognized separately is a good point; I may need to change my muscle memory and use <kbd>CTRL</kbd> for "pane" navigation and <kbd>ALT</kbd> for moving lines / etc.

**Comment by farzadmf** [comment]
Hey @booperlv , so I tried to take the plugin for a spin.

I enabled the plugin in `vimplug`:
```vimL
Plug 'booperlv/nvim-gomove'
```

I have this for the setup:
```lua
require("gomove").setup {
  -- whether or not to map default key bindings, (true/false)
  map_defaults = false,
  -- what method to use for reindenting, ("vim-move" / "simple" / ("none"/nil))
  reindent_mode = "vim-move",
  -- whether to not to move past end column when moving blocks horizontally, (true/false)
  move_past_end_col = false,
  -- whether or not to ignore indent when duplicating lines horizontally, (true/false)
  ignore_indent_lh_dup = true,
}
```

And finally I have the following mappings:
```vimL
nnoremap <M-H> <Plug>GoNSMLeft
nnoremap <M-J> <Plug>GoNSMDown
nnoremap <M-K> <Plug>GoNSMUp
nnoremap <M-L> <Plug>GoNSMRight

xnoremap <M-H> <Plug>GoVSMLeft
xnoremap <M-J> <Plug>GoVSMDown
xnoremap <M-K> <Plug>GoVSMUp
xnoremap <M-L> <Plug>GoVSMRight

nnoremap <C-h> <Plug>GoNSDLeft
nnoremap <C-j> <Plug>GoNSDDown
nnoremap <C-k> <Plug>GoNSDUp
nnoremap <C-l> <Plug>GoNSDRight

xnoremap <C-h> <Plug>GoVSDLeft
xnoremap <C-j> <Plug>GoVSDDown
xnoremap <C-k> <Plug>GoVSDUp
xnoremap <C-l> <Plug>GoVSDRight
```

But when I press <kbd>CTRL</kbd> + `h, j, k, l` of <kbd>Alt</kbd><kbd>Shift</kbd> + `h, j, k, l`, nothing happens :slightly_frowning_face: (normal or visual mode)

**Comment by booperlv** [comment]
Hello @farzadmf! My bad, I put the wrong snippet in the README. Just fixed that in the latest commit!
Instead, it should be
```
nmap <M-H> <Plug>GoNSMLeft
nmap <M-J> <Plug>GoNSMDown
nmap <M-K> <Plug>GoNSMUp
nmap <M-L> <Plug>GoNSMRight

xmap <M-H> <Plug>GoVSMLeft
xmap <M-J> <Plug>GoVSMDown
xmap <M-K> <Plug>GoVSMUp
xmap <M-L> <Plug>GoVSMRight

nmap <C-h> <Plug>GoNSDLeft
nmap <C-j> <Plug>GoNSDDown
nmap <C-k> <Plug>GoNSDUp
nmap <C-l> <Plug>GoNSDRight

xmap <C-h> <Plug>GoVSDLeft
xmap <C-j> <Plug>GoVSDDown
xmap <C-k> <Plug>GoVSDUp
xmap <C-l> <Plug>GoVSDRight
```

**Comment by farzadmf** [comment]
Awesome! It works great now :rocket: :rocket: :rocket: 

Thank you @booperlv for all the help, I was so happy with `vim-move`, but the duplicate feature of this plugin is a killer feature for me, great job
