### ISSUE TITLE
[Feature request] Delete with left of cursor text getting shifted rightwards

### ISSUE THREAD

**Issue by matu3ba** [booperlv/nvim-gomove#7]
This is a much missing feature on doing gaphical editing, ie with https://github.com/jbyuki/venn.nvim/issues/12

As I understand it, the plugin only provides moves but the goal is to make things more complete.
Since unfortunately neovim does not offer such "simple" features, it would be great to provide them consistently.

Side question:
Do you plan to provide a command to activate and deactivate the plugin like how venn.nvim works (buffer specific enabling via command)? This would make integration with buffer-specific setups much simpler.

**Comment by booperlv** [comment]
Not sure I'd be able to provide a delete operation within the plugin: but I'm really not sure I can completely understand what you'd like to achieve. If I may ask for another example: please do explain further the feature that you'd like in another example, thank you!

As for the side question: I do not plan to provide a command to do so within the plugin, as it can simply be handled through `nvim_buf_set_keymap`. Here's a snippet to do so!
```lua
function _G.Toggle_Gomove()
  local gomove_enabled = vim.b.gomove_enabled or false
  local buf_map = vim.api.nvim_buf_set_keymap
  if gomove_enabled == false then
    vim.b.gomove_enabled = true
    --move keymappings on hjkl
    buf_map(0, "n", "h", "<Plug>GoNSMLeft", {silent=true})
    buf_map(0, "n", "j", "<Plug>GoNSMDown", {silent=true})
    buf_map(0, "n", "k", "<Plug>GoNSMUp", {silent=true})
    buf_map(0, "n", "l", "<Plug>GoNSMRight", {silent=true})
    --duplicate keymappings on HJKL
    buf_map(0, "n", "H", "<Plug>GoNSDLeft", {silent=true})
    buf_map(0, "n", "J", "<Plug>GoNSDDown", {silent=true})
    buf_map(0, "n", "K", "<Plug>GoNSDUp", {silent=true})
    buf_map(0, "n", "L", "<Plug>GoNSDRight", {silent=true})
  else
    vim.cmd([[mapclear <buffer>]])
    vim.b.gomove_enabled = false
  end
  print('Gomove is', (vim.b.gomove_enabled and "enabled" or "disabled"))
end
--toggle with <leader>m
vim.api.nvim_set_keymap('n', '<leader>m', ":lua Toggle_Gomove()<CR>", {noremap=true, silent=true})
```

**Comment by matu3ba** [comment]
Okay, let me give you an example in venn.nvim with cursor position marked with x
1. One line of text before deletion
2. One line of text after deletion
3. Expected one line of text after deletion with the intended feature
```txt
test123 ─► tes123
    x
test23 ─► tes123
    x
 test23 ─► tes123
     x
```
The problem is that the arrow positions break every time, if I delete text and I need to jump leftwards and back to where I have removed some text.
Further, I dont want to count the amount of characters I deleted for making the spacing "just work" as this is tedious and annoying for longer words.
neovim provides also no quickjump on the same line, so that I can `I´ whitespace `Esc` and `C-o` which is another annoyance.

Personally I think this belongs into neovim core as this is a potential very frequent operation.

**Comment by booperlv** [comment]
I think I understand what you mean now! I don't think I can integrate this into gomove as it is very outside the scope of the plugin, but I will look into this and see if I can create it. Will keep the issue open for awhile to track progress :)

**Comment by booperlv** [comment]
Hello @matu3ba ! I was able to make a small implementation of this simply in functions :)
```lua
function _G.RightAlignDelete(register, count)
  local prev_pos = {vim.fn.line("."), vim.fn.col(".")}
  vim.cmd('normal!'..count..'"'..register..'x'..count..'I ')
  vim.fn.cursor(unpack(prev_pos))
end
api.nvim_set_keymap(
  'n', 'gd', ":lua RightAlignDelete(vim.v.register, vim.v.count1)<CR>", {silent=true}
)

function _G.RightAlignDeleteVirtual(register, count)
  local line_start = vim.fn.line("'<")
  local line_end = vim.fn.line("'>")

  vim.cmd('execute "normal! g`<\\<C-v>g`>"')

  vim.cmd('normal!'..count..'"'..register..'x')
  vim.cmd(line_start..','..line_end..'normal!'..count..'I ')

  vim.cmd('execute "normal! g`<\\<C-v>g`>"')
end
api.nvim_set_keymap(
  'x', 'gd', ":<C-u>lua RightAlignDeleteVirtual(vim.v.register, vim.v.count1)<CR>", {silent=true}
)
```
Edit: add support for registers
Simply place this snippet onto your init.lua and it should work! I haven't done any edge-case testing yet, but this should cover the base functionality at least. Hope this helps!

I made the mapping gd just because it's available, but you can remap it to anything you'd like :)

**Comment by matu3ba** [comment]
Thanks alot @booperlv !
I will try this out once I have more time for it.
