### ISSUE TITLE
Not working with cyrillic characters

### ISSUE THREAD

**Issue by lvim-tech** [booperlv/nvim-gomove#8]
Block move right not working with cyrillic characters
Left, Down, Up - works perfectly

**Comment by lvim-tech** [comment]
Block move right not working with cyrillic characters
Left, Down, Up - works perfectly

**Comment by booperlv** [comment]
Will look into this today and tell if I can reproduce it. Thank you!

**Comment by booperlv** [comment]
I can reproduce the issue but I am not exactly sure what is causing it. I do plan to refactor the block horizontal either way though, so I'll start working on it! Hopefully will close the issue with a fix soon:)

**Comment by lvim-tech** [comment]
Thanks in advance!

**Comment by booperlv** [comment]
Hello! I've been trying to fix this bug in my free time (i need more aaa) but to no avail thus far? I will keep trying though, just a status update. There is progress at the very least in what causes this - which is the existence of unicode characters that are two-character width. This may require individual handling with every line in a visual selection, so this will take me a bit longer!

**Comment by booperlv** [comment]
fixed this with the latest commit! 18254b4329ce424e8d5b59e6bb7c3f1fd404fb96

**Comment by lvim-tech** [comment]
Thanks for your work!
But moving on right...
![Screenshot from 2022-03-19 12-43-23](https://user-images.githubusercontent.com/82431193/159117898-4abde93d-47d8-4f7a-a164-5cef4037692b.png)
Not only cyrillic.

**Comment by booperlv** [comment]
Was able to fix it with Cyrillic characters taken into account for real @lvim-tech! Please do report if there're any more bugs found though. Thank you!

**Comment by lvim-tech** [comment]
Works perfect! Thank you, @booperlv !
